### PR TITLE
API Generator

### PR DESCRIPTION
**Pull request by nhtruong**
Program to generate and update OpenSearch JS Client with the newest from the OpenSearch OpenAPI Spec.

### Issues Resolved

Closes https://github.com/opensearch-project/opensearch-js/issues/789

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
I only did a cursory look of the generator code itself. Great work!

**Comment by dblock** [comment]
Take a pass at DEVELOPER_GUIDE and such as well.

**Comment by nhtruong** [comment]
Not sure why it keeps saying there's an error on line 52 of the `generate_api` workflow 🤔 
https://github.com/opensearch-project/opensearch-js/actions/runs/10853677637/workflow

**Comment by dblock** [comment]
> generate_api

VSCode says the `title` is not properly quoted (and `installation_id` is not a parameter to `tibdex/github-app-token@v2.1.0`, but that's above).

**Pull request merged**
