### PR TITLE
Fix issue #291

### PR DESCRIPTION
**Pull request by mmtdm**
### Description
This change initializes request headers by value, instead of reference, from connection headers. A test is added to confirm that correct behavior.

### Issues Resolved
https://github.com/opensearch-project/opensearch-js/issues/291

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nhtruong** [comment]
Looks good to me. Thank you for fixing this.
 `this.headers` should have been named `this.commonHeaders` for clarity.

**Comment by nhtruong** [comment]
Please rebase to resolve the failed Link Checker.

**Review by nhtruong — APPROVED** [review]

**Comment by nhtruong** [comment]
Hey @mmtdm, the commits chain you have looks very odd. It also includes a lot of previous commit.
Since this PR only 2 files update, I'd recommend:
- Create a new branch from the current main branch of your fork as backup.
- Re-sync your fork of this repo (This will delete the changes you currently have on main. Hence the previous step)
- Create a new branch from the new `main` branch of your fork,
- Cherry pick (or copy-paste) those 2 file changes in the backup branch into the new branch
- Close this PR and create a new one from said branch.

**Comment by mmtdm** [comment]
closing and re-opening with clean commit history

**Pull request closed without merging**
