### PR TITLE
[CCI][#206] renamed opensearchtypes CamelCase convention

### PR DESCRIPTION
**Pull request by BaurArabov**
### Description
renamed opensearchtypes to opensearchTypes due to the inconsistency in the naming convention of a module called "opensearchtypes".
This pull request updates the naming convention for the "opensearchtypes" module to follow the CamelCase naming convention used in OpenSearch Dashboards.

### Issues Resolved
https://github.com/opensearch-project/opensearch-js/issues/206

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nhtruong** [comment]
Thanks @BaurArabov 
Would you mind updating the changelog and remove the `package-lock.json`?
We're currently using yarn as our package manager. So, having `package-lock.json` will be confusing and might cause issues in the future.

**Comment by kavilla** [comment]
Can we have where we alias or map `opensearchtype` to `opensearchType` and make the before as deprecated. As is it would be a breaking change.

**Comment by nhtruong** [comment]
@BaurArabov: @kavilla is right. This must be marked as deprecated first before we can include this change in the next Major update of the client.

**Comment by nhtruong** [comment]
@BaurArabov The best way to do this is adding `opensearchTypes` with identical shape as `opensearchtypes`. Add a deprecation warning whenever `opensearchtypes` is used and direct the user to use `opensearchTypes` instead.

**Pull request closed without merging**
