### PR TITLE
[CCI] Create index_template guide

### LINKED ISSUE #471: [Guide] Index Template
Create `guides/index_template.md` similar to the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/index_template.md)

You must assure that: 
- All code-blocks, when run from start to finish in order they appear in the guide, do not throw any errors. If you want to demonstrate that certain statements will throw errors, they must be wrapped in a `try/catch` and print out the expected error.
- All code-blocks are properly marked with the language it's written in (i.e.  ` ```ruby `)
- The instructions, though mostly identical to the Ruby guide, are suitable for this repo.

### PR DESCRIPTION
**Pull request by Nicksqain**
### Description

- [x] Added index template guide

### Issues Resolved
- closes #471

### Check List

- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] Linter check was successfull - `yarn run lint` doesn't show any errors
- [x] Commits are signed per the DCO using --signoff
- [ ] Changelog was updated.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Nicksqain** [comment]
I didn't know how to describe the Client import, in opensearch-js it is used as relative. (e.g "../../")
I hope this is the right thing to doIf installing the package itself. Looking forward to your feedback :)

**Comment by nhtruong** [comment]
We don't need `error` callbacks for these guides. They distract from the main code.

**Comment by Nicksqain** [comment]
@nhtruong OK, thanks for the correction! I'll fix it now!

**Comment by Nicksqain** [comment]
@nhtruong Do I need to add a changelog entry? And if so, to which section and version?

**Review by nhtruong — APPROVED** [review]

**Pull request merged**
